-- 1. CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS Customer (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS TEXT,
    COMPANY_NAME VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- 2. CONTACTS TABLE
CREATE TABLE IF NOT EXISTS Contacts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    TITLE VARCHAR(100),
    POSITION VARCHAR(100),
    CONTACT_PREFERENCES TEXT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(ID) ON DELETE CASCADE
    );

-- 3. NOTES TABLE
CREATE TABLE IF NOT EXISTS Notes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AUTHOR VARCHAR(100) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(ID) ON DELETE CASCADE
    );

-- 4. INDEXES (For faster queries)
CREATE INDEX idx_customer_email ON Customer(EMAIL);
CREATE INDEX idx_contacts_customer ON Contacts(CUSTOMER_ID);
CREATE INDEX idx_notes_customer ON Notes(CUSTOMER_ID);
