package ozgur.crmTool.entities.concretes;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a Note in the system.
 * <p>
 * Each note is linked to a {@link Customer}, has textual content,
 * an author, and an active/inactive status.
 */
@Table(name="notes")
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Note {
    /**
     * Primary key of the note.
     * Auto-generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="id")
    private int id;

    /**
     * The customer associated with this note.
     * <p>
     * Many notes can belong to a single customer.
     * This relationship is mandatory (nullable = false).
     */
    @ManyToOne
    @JoinColumn(name="customer_id", nullable=false, referencedColumnName = "id")
    private Customer customer;

    /**
     * The main content/text of the note.
     */
    @Column(name="content")
    private String content;

    /**
     * The author of the note.
     */
    @Column(name="author")
    private String author;

    /**
     * Flag indicating whether the note is active.
     * <p>
     * - {@code true} means the note is active (default).
     * - {@code false} means the note has been soft deleted or deactivated.
     */
    @Column(name="is_active", nullable = false)
    private boolean isActive=true;
}
